// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show TagitrgetPlatform, TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBccfGtv-GeldM449eZ5DhVuAiSdXEPYB8',
    appId: '1:433905624034:android:c05739a91f9a098ddc4fbb',
    messagingSenderId: '433905624034',
    projectId: 'socialmedia-6c60c',
    storageBucket: 'socialmedia-6c60c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMIKDEK_xTfFKlkTzPQZ1In779T48ONwY',
    appId: '1:433905624034:ios:f0f938e9f8861825dc4fbb',
    messagingSenderId: '433905624034',
    projectId: 'socialmedia-6c60c',
    storageBucket: 'socialmedia-6c60c.firebasestorage.app',
    androidClientId: '433905624034-njisu47qgp8mpo3f4455c7ti3i3vko3j.apps.googleusercontent.com',
    iosClientId: '433905624034-i1t6vr457ok651sacfn77eat2midofsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaAppTask',
  );
}
